// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnRCEyYoKYd0UL23NU2fEHSEn3rINz_0M',
    appId: '1:44912727159:web:e431f435f50e6eec326272',
    messagingSenderId: '44912727159',
    projectId: 'stellarhub-3ea81',
    authDomain: 'stellarhub-3ea81.firebaseapp.com',
    storageBucket: 'stellarhub-3ea81.firebasestorage.app',
    measurementId: 'G-7L8JWTJZ8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU5zgIvurhg8fQpMgjmNbLy8aiapOxm2g',
    appId: '1:44912727159:android:d2a532f89c7394ef326272',
    messagingSenderId: '44912727159',
    projectId: 'stellarhub-3ea81',
    storageBucket: 'stellarhub-3ea81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVyCsseMqmOgGVudFOFKdOc2qw9JcybSY',
    appId: '1:44912727159:ios:c1ad72ecf5d4e279326272',
    messagingSenderId: '44912727159',
    projectId: 'stellarhub-3ea81',
    storageBucket: 'stellarhub-3ea81.firebasestorage.app',
    iosClientId: '44912727159-ha167djsk9mqa201vvgncuni40d2rteq.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVyCsseMqmOgGVudFOFKdOc2qw9JcybSY',
    appId: '1:44912727159:ios:c1ad72ecf5d4e279326272',
    messagingSenderId: '44912727159',
    projectId: 'stellarhub-3ea81',
    storageBucket: 'stellarhub-3ea81.firebasestorage.app',
    iosClientId: '44912727159-ha167djsk9mqa201vvgncuni40d2rteq.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnRCEyYoKYd0UL23NU2fEHSEn3rINz_0M',
    appId: '1:44912727159:web:7821fef5813ad240326272',
    messagingSenderId: '44912727159',
    projectId: 'stellarhub-3ea81',
    authDomain: 'stellarhub-3ea81.firebaseapp.com',
    storageBucket: 'stellarhub-3ea81.firebasestorage.app',
    measurementId: 'G-5D69EB47E2',
  );
}
